<script>
function formation(members, songs, snapshots) {
    return {
        members, songs, snapshots,
        slots: [null, null, null, null, null], active: 0, search: '', band: '', songId: 0,
        modal: false, pending: null,
        setup: {level: 1, training: 0, awakening: 0, skillLevel: 1, snapshotId: 0, snapshotLevel: 1, snapshotRank: 0, snapshotSkillLevel: 1},
        rates: {
            1: {1:.4086,30:.6571,40:.7429,50:.8286,70:1},
            2: {1:.4075,30:.625,40:.7,50:.775,70:.925,80:1},
            3: {1:.4067,30:.6,40:.6667,50:.7333,70:.8667,80:.9333,90:1},
            4: {1:.4067,30:.6,40:.6667,50:.7333,70:.8667,80:.9333,90:1},
            5: {1:.4067,30:.6,40:.6667,50:.7333,70:.8667,80:.9333,90:1},
        },
        get chosenSong(){ return this.songs.find(s => s.id === this.songId) || null },
        get bands(){ return [...new Set(this.members.map(m => m.character.band))] },
        get selectedCharacterIds(){ return this.slots.map((m,i) => i === this.active ? null : m?.character_id).filter(Boolean) },
        get selectedSnapshotIds(){ return this.slots.map((m,i) => i === this.active ? null : m?.snapshot?.id).filter(Boolean) },
        get filtered(){ return this.members.filter(m => !this.selectedCharacterIds.includes(m.character_id) && (!this.band || m.character.band === this.band) && (!this.search || (m.name+m.character.name).includes(this.search))) },
        baseMax(m){ return ({2:30,3:40,4:50})[m.rarity_id] || 50 },
        finalMax(m){ return ({2:70,3:80,4:90})[m.rarity_id] || 90 },
        get setupMaxLevel(){ return Math.min(this.finalMax(this.pending), this.baseMax(this.pending) + this.setup.training * 10) },
        snapshotBaseMax(s){ return ({1:30,2:40,3:50,5:50})[s?.level_growth] || 50 },
        snapshotFinalMax(s){ return ({1:70,2:80,3:90,5:90})[s?.level_growth] || 90 },
        get pendingSnapshot(){ return this.snapshots.find(s => s.id === this.setup.snapshotId) || null },
        get snapshotMaxLevel(){ let s=this.pendingSnapshot; return s ? Math.min(this.snapshotFinalMax(s),this.snapshotBaseMax(s)+this.setup.snapshotRank*10) : 1 },
        characterMatches(s,m){ let clean=v=>String(v||'').replace(/\s/g,'').split(/[\/·,]/).filter(x=>x.length>1); let a=clean(s.character_name),b=clean(m.character.name); return a.some(x=>b.some(y=>x.includes(y)||y.includes(x))) },
        get availableSnapshots(){ return this.pending ? this.snapshots.filter(s => this.characterMatches(s,this.pending) && !this.selectedSnapshotIds.includes(s.id)) : [] },
        growthRate(key,level){ let points=Object.entries(this.rates[key]||this.rates[3]).map(([l,r])=>[+l,+r]).sort((a,b)=>a[0]-b[0]), exact=points.find(p=>p[0]===level); if(exact)return exact[1]; let lo=points[0],hi=points.at(-1); for(let i=1;i<points.length;i++)if(level<points[i][0]){lo=points[i-1];hi=points[i];break} return lo[1]+(hi[1]-lo[1])*(level-lo[0])/(hi[0]-lo[0]) },
        configuredStat(m,k,level,training,awakening){ let maximum=+m['max_'+k]||0; return maximum?Math.round(maximum*(this.growthRate(m.rarity_id,level)+(training+awakening)*.025)):+m[k] },
        snapshotStat(s,k,level,rank){ return s?Math.round((+s[k]||0)*this.growthRate(s.level_growth,level)*(1+rank*.025)):0 },
        pendingStat(k){ return this.pending?this.configuredStat(this.pending,k,this.setup.level,this.setup.training,this.setup.awakening):0 },
        get pendingTotal(){ return ['performance','technique','visual'].reduce((n,k)=>n+this.pendingStat(k),0) },
        get pendingSnapshotTotal(){ let s=this.pendingSnapshot; return ['performance','technique','visual'].reduce((n,k)=>n+this.snapshotStat(s,k,this.setup.snapshotLevel,this.setup.snapshotRank),0) },
        power(m){ return m.display_power },
        prepare(m){ if(this.selectedCharacterIds.includes(m.character_id))return; this.pending=m; this.setup={level:this.baseMax(m),training:0,awakening:0,skillLevel:1,snapshotId:0,snapshotLevel:1,snapshotRank:0,snapshotSkillLevel:1}; this.modal=true },
        openSlot(index){ this.active=index; let m=this.slots[index]; if(m){this.pending=m;this.setup={level:m.level,training:m.training,awakening:m.awakening,skillLevel:m.skillLevel,snapshotId:m.snapshot?.id||0,snapshotLevel:m.snapshotLevel||1,snapshotRank:m.snapshotRank||0,snapshotSkillLevel:m.snapshotSkillLevel||1};this.modal=true} },
        closeModal(){ this.modal=false; this.pending=null },
        setTraining(training){ this.setup.training=training; this.setup.level=Math.min(this.setup.level,this.setupMaxLevel) },
        chooseSnapshot(s){ if(this.selectedSnapshotIds.includes(s.id))return;this.setup.snapshotId=s.id;this.setup.snapshotRank=0;this.setup.snapshotLevel=this.snapshotBaseMax(s);this.setup.snapshotSkillLevel=1 },
        clearSnapshot(){ this.setup.snapshotId=0;this.setup.snapshotLevel=1;this.setup.snapshotRank=0;this.setup.snapshotSkillLevel=1 },
        setSnapshotRank(rank){ this.setup.snapshotRank=rank;this.setup.snapshotLevel=Math.min(this.setup.snapshotLevel,this.snapshotMaxLevel) },
        levelText(groups,level){ return (groups||[]).map(g=>g?.[level]||g?.[String(level)]).filter(Boolean) },
        selectedSkill(m,l){ return m?.live_skill_levels?.[l]||m?.live_skill_levels?.[String(l)]||m?.live_skill||'해당 스킬 없음' },
        selectedLeaderSkill(m,l){ return m?.leader_skill_levels?.[l]||m?.leader_skill_levels?.[String(l)]||m?.leader_skill||'해당 스킬 없음' },
        selectedGekisouSkill(m,l){ return m?.gekisou_skill_levels?.[l]||m?.gekisou_skill_levels?.[String(l)]||m?.gekisou_skill||'해당 스킬 없음' },
        percentages(text){ return [...String(text||'').replace(/<[^>]*>/g,' ').matchAll(/([0-9]+(?:\.[0-9]+)?)\s*%/g)].map(x=>+x[1]) },
        scorePercent(m,l){ let v=this.percentages(this.selectedSkill(m,l));return v.length?Math.max(...v):(+m.score_up||0) },
        get pendingScoreUp(){ return this.pending?this.scorePercent(this.pending,this.setup.skillLevel):0 },
        confirmMember(){ if(!this.pending||this.selectedCharacterIds.includes(this.pending.character_id)||this.selectedSnapshotIds.includes(this.setup.snapshotId))return; let s=this.pendingSnapshot, stats={}; ['performance','technique','visual'].forEach(k=>stats['display_'+k]=this.pendingStat(k)+this.snapshotStat(s,k,this.setup.snapshotLevel,this.setup.snapshotRank)); let m={...this.pending,...stats,level:this.setup.level,training:this.setup.training,awakening:this.setup.awakening,skillLevel:this.setup.skillLevel,snapshot:s,snapshotLevel:this.setup.snapshotLevel,snapshotRank:this.setup.snapshotRank,snapshotSkillLevel:this.setup.snapshotSkillLevel,selected_live_skill:this.selectedSkill(this.pending,this.setup.skillLevel),selected_leader_skill:this.selectedLeaderSkill(this.pending,this.setup.awakening+1),selected_gekisou_skill:this.selectedGekisouSkill(this.pending,this.setup.skillLevel),selected_score_up:this.pendingScoreUp,snapshot_support:this.levelText(s?.support_skill_levels,this.setup.snapshotSkillLevel).join('<hr>'),snapshot_gekisou:this.levelText(s?.gekisou_support_levels,this.setup.snapshotSkillLevel).join('<hr>')}; m.display_power=m.display_performance+m.display_technique+m.display_visual;this.slots[this.active]=m;this.slots=[...this.slots];this.closeModal();let n=this.slots.findIndex(x=>!x);if(n>=0)this.active=n },
        reset(){ this.slots=[null,null,null,null,null];this.active=0;this.closeModal() },
        sum(k){ return this.slots.filter(Boolean).reduce((a,m)=>a+m['display_'+k],0) },
        get bonus(){ let c={};this.slots.filter(Boolean).forEach(m=>c[m.character.band]=(c[m.character.band]||0)+1);let n=Math.max(0,...Object.values(c));return n===5?15:n>=3?5:0 },
        get leaderBonus(){ let leader=this.slots[2];if(!leader)return 0;let v=this.percentages(leader.selected_leader_skill);return v.length?Math.max(...v):0 },
        get total(){ let raw=this.sum('performance')+this.sum('technique')+this.sum('visual');return Math.round(raw*(1+this.bonus/100)*(1+this.leaderBonus/100)) },
        comboRate(i){ return i<=20?1:i<=50?1.01:i<=100?1.02:i<=150?1.03:i<=200?1.04:i<=250?1.05:i<=300?1.06:i<=400?1.07:i<=500?1.08:i<=600?1.09:i<=700?1.10:1.11 },
        get baseScore(){ let s=this.chosenSong,n=s?.note_count||0;if(!s||!n||!this.total)return 0;let per=this.total*3*(1+(s.expert-5)*.01)/n,score=0;for(let i=1;i<=n;i++)score+=Math.floor(per*1.1*this.comboRate(i));return score },
        skillDurationText(text){ let hit=String(text||'').replace(/<[^>]*>/g,'').match(/([0-9]+(?:\.[0-9]+)?)초간/);return +(hit?.[1]||5) },
        get estimatedSongDuration(){ let s=this.chosenSong;if(!s)return 120;let bpm=+(String(s.bpm||'160').match(/[0-9]+(?:\.[0-9]+)?/)?.[0]||160);return Math.max(90,Math.min(180,s.note_count/(bpm*1.5)*60)) },
        skillBoost(text){ let p=this.percentages(text);return (p.length?Math.max(...p):0)/100*(this.skillDurationText(text)/this.estimatedSongDuration) },
        get skillScore(){ if(!this.baseScore)return 0;let boost=this.slots.filter(Boolean).reduce((sum,m)=>{let live=(m.selected_score_up/100)*(this.skillDurationText(m.selected_live_skill)/this.estimatedSongDuration)*(this.slots.indexOf(m)===2?2:1);return sum+live+this.skillBoost(m.selected_gekisou_skill)+this.skillBoost(m.snapshot_support)+this.skillBoost(m.snapshot_gekisou)},0);return Math.round(this.baseScore*(1+boost)) },
        snapshotsFor(m){ return this.snapshots.filter(s=>this.characterMatches(s,m)) },
        bestSnapshotFor(m,used=new Set){ return this.snapshotsFor(m).filter(s=>!used.has(s.id)).map(s=>({s,p:['performance','technique','visual'].reduce((n,k)=>n+this.snapshotStat(s,k,this.snapshotFinalMax(s),4),0)+this.percentages(this.levelText(s.support_skill_levels,5).join(' ')).reduce((a,v)=>a+v,0)*25})).sort((a,b)=>b.p-a.p)[0]?.s||null },
        recommendedCard(m,used=new Set){ let s=this.bestSnapshotFor(m,used);if(s)used.add(s.id);let stats={};['performance','technique','visual'].forEach(k=>stats['display_'+k]=this.configuredStat(m,k,this.finalMax(m),4,4)+this.snapshotStat(s,k,this.snapshotFinalMax(s),4));let card={...m,...stats,level:this.finalMax(m),training:4,awakening:4,skillLevel:5,snapshot:s,snapshotLevel:s?this.snapshotFinalMax(s):1,snapshotRank:s?4:0,snapshotSkillLevel:s?5:1,selected_live_skill:this.selectedSkill(m,5),selected_leader_skill:this.selectedLeaderSkill(m,5),selected_gekisou_skill:this.selectedGekisouSkill(m,5),selected_score_up:this.scorePercent(m,5),snapshot_support:this.levelText(s?.support_skill_levels,5).join('<hr>'),snapshot_gekisou:this.levelText(s?.gekisou_support_levels,5).join('<hr>')};card.display_power=card.display_performance+card.display_technique+card.display_visual;return card },
        uniqueSnapshotTeam(team){ let used=new Set;return team.map(card=>this.recommendedCard(card,used)) },
        teamScore(team){ let before=this.slots;this.slots=team;let score=this.skillScore;this.slots=before;return score },
        recommendFormation(){ if(!this.chosenSong)return;let byCharacter=new Map;this.members.forEach(m=>{let card=this.recommendedCard(m),utility=card.display_power*(1+card.selected_score_up/100*.05)+this.percentages(card.selected_leader_skill).reduce((a,v)=>Math.max(a,v),0)*120;if(!byCharacter.has(m.character_id)||utility>byCharacter.get(m.character_id).utility)byCharacter.set(m.character_id,{card,utility})});let pool=[...byCharacter.values()].sort((a,b)=>b.utility-a.utility),teams=[];let add=(cards)=>{if(cards.length===5)teams.push(this.uniqueSnapshotTeam(cards))};add(pool.slice(0,5).map(x=>x.card));this.bands.forEach(b=>add(pool.filter(x=>x.card.character.band===b).slice(0,5).map(x=>x.card)));pool.forEach(({card:leader})=>{let rest=pool.filter(x=>x.card.character_id!==leader.character_id).slice(0,4).map(x=>x.card),team=[rest[0],rest[1],leader,rest[2],rest[3]];add(team)});let best=teams.map(team=>({team,score:this.teamScore(team)})).sort((a,b)=>b.score-a.score)[0];if(best){this.slots=best.team;this.active=0} },
        number(n){ return new Intl.NumberFormat('ko-KR').format(Math.round(n||0)) },
    }
}
</script>
