<x-layouts.wiki :title="'멤버'">
    <div class="mx-auto grid max-w-[1280px] gap-4 px-4 py-5 lg:grid-cols-[220px_minmax(0,1fr)] lg:px-6">
        <aside><form class="overflow-hidden rounded-lg border border-slate-200 bg-white lg:sticky lg:top-28"><div class="border-b p-3"><input name="q" value="{{ request('q') }}" placeholder="이름 검색" class="w-full rounded border-slate-200 bg-slate-50 px-3 py-2 text-xs focus:border-[#6c5ce7] focus:ring-[#6c5ce7]"></div><div class="border-b p-3"><label class="text-[10px] font-bold text-slate-400">밴드</label><select name="band" class="mt-2 w-full rounded border-slate-200 text-xs"><option value="">전체 밴드</option>@foreach($bands as $band)<option @selected(request('band')===$band)>{{ $band }}</option>@endforeach</select></div><div class="border-b p-3"><label class="text-[10px] font-bold text-slate-400">카드 타입</label><div class="mt-2 space-y-1">@foreach(['레드','블루','그린','옐로우','퍼플'] as $type)<label class="flex items-center gap-2 rounded px-2 py-1.5 text-xs hover:bg-slate-50"><input type="radio" name="type" value="{{ $type }}" @checked(request('type')===$type) class="text-[#6c5ce7] focus:ring-[#6c5ce7]"><x-type-icon :type="$type" size="sm" />{{ $type }}</label>@endforeach</div></div><div class="border-b p-3"><label class="text-[10px] font-bold text-slate-400">희귀도</label><div class="mt-2 grid grid-cols-3 gap-1">@foreach($rarities as $rarity)<label class="flex cursor-pointer items-center justify-center rounded-sm border border-slate-200 p-2 transition hover:border-[#8b7cf6] has-[:checked]:border-[#8b7cf6] has-[:checked]:bg-[#6c5ce7]/10"><input type="radio" name="rarity" value="{{$rarity}}" @checked(request('rarity')===$rarity) class="sr-only"><x-rarity-icon :rarity="$rarity" size="sm" /></label>@endforeach</div></div><div class="p-3"><button class="w-full rounded bg-[#6c5ce7] py-2 text-xs font-bold text-white">필터 적용</button><a href="{{ route('members.index') }}" class="mt-2 block text-center text-[10px] text-slate-400">초기화</a></div></form></aside>
        <section class="min-w-0"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            @forelse($members as $member)
                <a href="{{ route('members.show',$member) }}" class="group overflow-hidden rounded-lg border border-slate-200 bg-white transition hover:-translate-y-0.5 hover:border-[#aaa0ee] hover:shadow-lg">
                    <div class="relative aspect-[3/4] overflow-hidden bg-slate-100">@if($member->image_url)<img src="{{ $member->image_url }}" alt="{{ $member->name }}" class="h-full w-full object-cover transition duration-300 group-hover:scale-[1.02]" loading="lazy">@else<div class="grid h-full place-items-center text-6xl font-black text-white" style="background:{{ $member->character->color }}">{{ mb_substr($member->character->name,0,1) }}</div>@endif<div class="absolute left-3 top-3 flex items-center gap-2 rounded-md bg-black/55 px-2 py-1.5 backdrop-blur"><x-rarity-icon :rarity="$member->rarity" :name="$member->name" :source-id="$member->source_id" size="sm" /><x-type-icon :type="$member->type" size="sm" /></div></div>
                    <div class="p-3"><x-band-logo :band="$member->character->band" size="sm" /><h2 class="mt-2 truncate text-sm font-black">{{ $member->name }}</h2><p class="mt-0.5 text-[10px] text-slate-400">{{ $member->character->name }}</p><div class="mt-3 grid grid-cols-2 border-t pt-2 text-[10px]"><span class="text-slate-400">{{ $member->skill_type }} <b class="text-[#6c5ce7]">+{{ $member->score_up }}%</b></span><span class="text-right text-slate-400">종합력 <b class="text-slate-700">{{ number_format($member->power) }}</b></span></div></div>
                </a>
            @empty<div class="col-span-full rounded-lg border bg-white p-14 text-center text-xs text-slate-400">조건에 맞는 멤버가 없습니다.</div>@endforelse
        </div><div class="mt-5">{{ $members->links() }}</div></section>
    </div>
</x-layouts.wiki>
